In [1]:
import numpy as np
import numpy.linalg as LA

In [20]:
R = [[-0.9743376, -0.0255771, -0.2236337],
     [0.0967244, -0.9446929, -0.3133683],
     [-0.2032501, -0.3269574,  0.9229237]]

R = [[ -1.0000000, -0.0000000,  0.0000000],
     [  0.0000000, -1.0000000,  0.0000000],
     [   0.0000000,  0.0000000,  1.0000000 ]]

R = [[ 0, -0.8,  -0.6],
     [ 0.8, -0.36,  0.48],
     [ 0.6, 0.48,  -0.64]]

R = np.array(R)
RT = R.T
RI = LA.inv(R)

print(RT)
print(RI)

[[ 0.    0.8   0.6 ]
 [-0.8  -0.36  0.48]
 [-0.6   0.48 -0.64]]
[[ 0.    0.8   0.6 ]
 [-0.8  -0.36  0.48]
 [-0.6   0.48 -0.64]]


In [19]:
p = np.array([10, 10, 10])

print(R @ p)
print(RT @ p)
print(RI @ R @ p)

[-10. -10.  10.]
[-10. -10.  10.]
[10. 10. 10.]


In [19]:
R = np.matrix([[0.99, -0.04, 0.85],
     [0.03, 0.09, 0.10],
     [0.31, -0.59, -0.73]])

R = np.matrix([
    [0.85, 0.044, 0.3884],
    [0.0586, 0.9822, -0.30],
    [0.52, -0.1828, -0.87]])

In [18]:
X = np.array([0.057, 0.464, 0.884])

In [20]:
np.matmul(R, X)

matrix([[ 0.4122116,  0.193881 , -0.8242592]])

# Optical Axis Listing's Law

In [3]:
OPT = np.array([0.1718,   -0.1984,   -0.9649])

In [15]:
def toMat(opt):
    opt = -opt
    sp = -opt[1]
    cpsq = 1 - sp**2
    stcp = -opt[0]
    ctcp = opt[2]
    
    r11 = 1 - ( stcp**2 / (1+ctcp))
    r12 = -sp*stcp / (1+ctcp)
    r21 = -sp*stcp / (1+ctcp)
    r22 = (ctcp + cpsq) / (1+ ctcp)
    r31 = stcp
    r32 = sp
    
    return np.array([r11, r12, stcp, r21, r22, sp, r31, r32, -ctcp]).reshape(3,3)
    

In [16]:
R = toMat(OPT)
print(R)

[[ 0.98497876  0.017347    0.1718    ]
 [ 0.017347    0.97996714 -0.1984    ]
 [ 0.1718     -0.1984     -0.9649    ]]
