In [6]:
import random
import numpy as np

import torch 
import torch.nn as nn
import torch.nn.functional as F

# Global Average Pooling

In [3]:
def GlobalAveragePooling(x):
    return x.mean(-1).mean(-1)  

In [4]:
#
# mean 처리 방식 (이거 시각화 도구 있으면 좋겠다)
#
x = torch.tensor(
    [[9, 9, 9, 9], 
     [1, 1, 1, 1], 
     [2, 2, 2, 2]])
x = x.double()
print(x)
print(x.shape)
print(x.mean())     # 개별 요소 전체 평균
print(x.mean(0))    # shape[0:i]에 대해 평균
print(x.mean(-1))   # sahpe[i:-1(==1)]에 대해 평균
print(x.mean(-2))

tensor([[9., 9., 9., 9.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.]], dtype=torch.float64)
torch.Size([3, 4])
tensor(4., dtype=torch.float64)
tensor([4., 4., 4., 4.], dtype=torch.float64)
tensor([9., 1., 2.], dtype=torch.float64)
tensor([4., 4., 4., 4.], dtype=torch.float64)


# Swap Axis

In [11]:
def swap_axis(x, axis_a, axis_b):
    return torch.transpose(x, axis_a, axis_b)

In [13]:
# 예제
x = torch.randn(2, 3)
print(x)
print(x.shape)

t = torch.transpose(x, 0, 1)
print(t.shape)
print(t)
print(swap_axis(x, 0, 1))

tensor([[-0.0822, -0.3769, -1.1875],
        [ 2.0213,  1.3895,  0.3384]])
torch.Size([2, 3])
torch.Size([3, 2])
tensor([[-0.0822,  2.0213],
        [-0.3769,  1.3895],
        [-1.1875,  0.3384]])
tensor([[-0.0822,  2.0213],
        [-0.3769,  1.3895],
        [-1.1875,  0.3384]])


# Initial Seed

In [3]:
def setup_seed(seed):
    """
    랜덤 시드를 세팅하더라도 worker가 0이 아닌 경우에(?) 다소 차이가 있다고 함
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    
    # if you are suing GPU
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # discuss.pytorch.org/t/random-seed-initialization/7854/16 suggest
    torch.backends.cudnn.enabled = False 
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

In [4]:
def worker_init_fn(worker_id):
    # Custom worker init to not repeat pairs
    np.random.seed(np.random.get_state()[1][0] + worker_id)