# Camera Calibration w/ distortion coefficient



# import

In [1]:
import sys
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [21]:
sys.path.append("../../../")

%run ../../../ac/math/angles.py
%run ../../../ac/visualizer/plotter.py
%run ../../../al/optics/projection.py
%run ../../../al/optics/calibration.py
%run ../../../al/optics/parameter.py

<Figure size 432x288 with 0 Axes>

In [6]:
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

# Calibration Reference

<br>

- [OpenCV 캘리브레이션 레퍼런스](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html)
- [위키 - 카메라 해부 px/mm ](https://en.wikipedia.org/wiki/Camera_resectioning)
- [OpenCV Tutorial Git](https://github.com/opencv/opencv/blob/master/samples/python/calibrate.py)

# Undistorted

<br>

- [Why we use getOptimalNewCameraMatrix](http://answers.opencv.org/question/101398/what-does-the-getoptimalnewcameramatrix-function-does/)
- 디바이스 렌즈 인스턴스 별로 radial distortion 계수는 같은지 체크

<br>


# Calibration Nexus-5x 

### 참고 
- resolution 마다 Intrinsic Parameter와 distortion coefficients가 다르다.
- 이론적으로는 왜곡 계수는 해상도와 무관하다. [5절 참고](http://darkpgmr.tistory.com/32)
- 기하 계산을 위해서는 오토 포커싱은 꺼놓고 진행해야 한다
- 주점(cx, cy)이 실제 값보다 절반으로 나오는 현상 해결법 - 캘리할 때 다양한 각도의 이미지가 더 필요

<br>

### Nexus-5x 후면 카메라


|resolution|fx|cx|fy|cy|k1|k2|p1|p2|k3|
|---|---|---|---|---|---|---|---|---|---|
|1200x1600|1221|598.071|1222|804.72|0.136|-0.555|0.0047|0.0003|0.3525|
|3024x4032|2685|1848|2690|2007|-0.37|3.589|-0.022| 0.01|-9.69|

<br>

### Nexus-5x 전면 카메라

|resolution|fx|cx|fy|cy|k1|k2|p1|p2|k3|
|---|---|---|---|---|---|---|---|---|---|
|1920x1080|1433.4389|587.7184|1437.476|604.914|-0.4355|0.6174|-0.0008|-0.0049|-0.3697|
|1080x720|946.2767|612.9987|950.3305|326.0792|0.0438|-0.6156|-0.0125|-0.004|0.5669|

<br>

In [14]:
base_path = "/home/chy/dev-bench/auto-catch/notes/research/visual-optics/samples/{}"

In [30]:
sample_path = base_path.format("nexus-5x-front-1920-1080/")
camera_mat, distort_coefs, _, _, imgs = calibration(sample_path, 7, 5, True)
print("1920x1080 param:\n{}".format(camera_mat))
print("1920x1080 distortion coef:\n{}".format(distort_coefs))

1920x1080 param:
[[1433.4389    0.      587.7184]
 [   0.     1437.476   604.914 ]
 [   0.        0.        1.    ]]
1920x1080 distortion coef:
[[-0.4355  0.6174 -0.0008 -0.0049 -0.3697]]


In [31]:
# 1280 x 720???
sample_path = base_path.format("nexus-5x-front-1080-720/")
camera_mat, _, _, _, imgs = calibration(sample_path, 7, 5, True)
print("1080x720 param:\n{}".format(camera_mat))
print("1080x720 distortion coef:\n{}".format(distort_coefs))

1080x720 param:
[[946.2767   0.     612.9987]
 [  0.     950.3305 326.0792]
 [  0.       0.       1.    ]]
1080x720 distortion coef:
[[-0.4355  0.6174 -0.0008 -0.0049 -0.3697]]
