In [1]:
import numpy as np
import pandas as pd

In [2]:
np.set_printoptions(precision=5)
np.set_printoptions(suppress=True)

In [3]:
opt_params = np.array([
    [
		[-13.618681046323532, 6.108521398761689, -10.967845318912032, 0.01744479024098773, 0.01728295883754014],
		[-13.50423589788311, 5.611471028422714, -11.113456939438754, 0.017597350487051175, 0.01809869804901151],
		[-13.645267297752502, 5.66366006192978, -11.091579189877768, 0.01746511659224787, 0.017677883756909898],
		[-13.418192903151933, 5.230269032498841, -11.16669006251825, 0.017480901592373067, 0.01772874719921944], 
		[-13.381966011250105, 4.9390911334042915, -11.139041834521938, 0.017498988545248936, 0.017714411199164292],
		[-13.095528845641779, 4.6549681671094705, -11.210711863930237, 0.01745950351093433, 0.017570369656774755], 
    ],
    [
		[-13.760547235790362, 5.646952420121197, -10.998083212301188, 0.017454811169672593, 0.017464233119129216],
		[-13.903727374182175, 5.77010604955139, -11.010680324471098, 0.017462252498098386, 0.017508855949670388],
		[-13.660710564835956, 5.753617040893886, -11.036205811130628, 0.017466760720739598, 0.017541360111758032], 
		[-13.777088115259795, 5.436006967708112, -11.061234545616642, 0.017474543272911845, 0.01753721165382419], 
		[-13.613743605183243, 4.952466317182889, -11.115469848957241, 0.017454266519528864, 0.017567219933908862], 
		[-13.322519529211853, 4.110848507302089, -11.113889003323028, 0.017463870521691474, 0.01762656097602673],
     ],
    [                                                                                                       
		[-13.759023016581393, 5.7776795048077885, -10.93801133179232, 0.017387991098977883, 0.017155537362661726], 
		[-13.898073892366604, 5.798904905113546, -10.963209247101991, 0.017443016745973813, 0.017333961058565064] ,
		[-14.051031173486205, 5.7728388090936535, -10.970351342748641, 0.01745161892908856, 0.01741169040186409] ,
		[-13.946800268840642, 5.556360283805267, -10.987231956072492, 0.01745251354081232, 0.017463430655712334] ,
		[-13.558547143158385, 5.299152325836126, -11.007890444326218, 0.017464369870178405, 0.01744508669264354] ,
		[-13.432817772314607, 4.41008544439142, -11.004111380417614, 0.017452028101207145, 0.017447383490108655] ,
     ],
    [                                                                                                       
		[-13.940788236598657, 5.766151825356606, -10.874820655660358, 0.017165014124766637, 0.01663901135461554] ,
		[-14.021796919381739, 5.741595354642247, -10.877612702398519, 0.017323025217072775, 0.016923003769646935] ,
		[-14.482551603372247, 5.726474635073642, -10.924118318302513, 0.017441345431956138, 0.017273518970889072] ,
		[-13.95974698887744, 5.178288814155374, -10.853537441995222, 0.01744224996731578, 0.017244748863799817] ,
		[-13.752373483721557, 4.418072691947858, -10.72116970089774, 0.017313680396128288, 0.016620586181136966] ,
		[-13.618156438491095, 3.9237922718597793, -10.703775533954868, 0.01733561789286358, 0.01669584116378836] ,
     ],
    [                                                                                                       
		[-14.241249935520113, 5.8034093372976985, -10.845732628503985, 0.01680658043550468, 0.016214203510119887] ,
		[-14.09173976687877, 5.18028405766077, -10.460995154373684, 0.015690839522531606, 0.013507904313928095] ,
		[-14.02147735595806, 5.226346250088885, -10.601832141626353, 0.016501042231492173, 0.015213622145931341] ,
		[-14.078584626443398, 5.035700981729965, -10.62019621984512, 0.017047619473446348, 0.01593648820254574] ,
		[-13.868024510416621, 4.755385961371166, -10.657483540017294, 0.017316233976916028, 0.01661468781537858] ,
		[-13.692624792507887, 3.9059916235169356, -10.514099566098023, 0.017161094777851615, 0.016023014228948015], 
     ],
    [                                                                                                       
		[-13.868146023867086, 5.654482831635007, -10.621630791366027, 0.01610431480303165, 0.014854140024672252] ,
		[-14.000237032152905, 5.507353567519972, -10.588117321401405, 0.016691603198294526, 0.015318685881038298] ,
		[-14.35640844704098, 5.5968699748175315, -10.721916288150574, 0.017147891662629183, 0.016362372356986354] ,
		[-14.256140021187955, 5.134792662606065, -10.547670109060958, 0.0167626501330163, 0.01538824852321258] ,
		[-14.050307651693645, 4.893171283170781, -10.549434726008394, 0.01727020549279766, 0.016400865405831782], 
		[-14.138614714727343, 4.358009059899244, -10.55229824159386, 0.017432691868934883, 0.01711303915988582] ,
]])

In [4]:
print(opt_params.shape)

(6, 6, 5)


In [5]:
# rad to degree 변환 
opt_deg_params = opt_params.copy()
opt_deg_params[:,:,3:5] = np.rad2deg(opt_deg_params[:,:,3:5])

In [6]:
# degree 변환 확인
opt_deg_params[0,0,3:5]

array([0.99951, 0.99024])

In [13]:
# 델타, 카파(deg) 수치 절삭
opt_deg_params = np.round(opt_deg_params, 2)

In [14]:
# 수치 절삭 확인
opt_deg_params[0,0,0:3]

array([-13.62,   6.11, -10.97])

In [15]:
# 스크린 열 / 행 
opt_deg_dict = { 
    str.format('C{}', c) : { str.format('R{}', r) : row for r, row in enumerate(col) } 
    for c, col in enumerate(opt_deg_params) }

In [16]:
# 열/행 dict 확인
opt_deg_dict['C0']['R0']

array([-13.62,   6.11, -10.97,   1.  ,   0.99])

In [17]:
# 데이터 프레임 변환
df_opt_params = pd.DataFrame(opt_deg_dict)

In [18]:
# 데이터 프레임 확인
df_opt_params

C0                                 C1  \
R0  [-13.62, 6.11, -10.97, 1.0, 0.99]    [-13.76, 5.65, -11.0, 1.0, 1.0]   
R1  [-13.5, 5.61, -11.11, 1.01, 1.04]    [-13.9, 5.77, -11.01, 1.0, 1.0]   
R2  [-13.65, 5.66, -11.09, 1.0, 1.01]  [-13.66, 5.75, -11.04, 1.0, 1.01]   
R3  [-13.42, 5.23, -11.17, 1.0, 1.02]   [-13.78, 5.44, -11.06, 1.0, 1.0]   
R4  [-13.38, 4.94, -11.14, 1.0, 1.01]  [-13.61, 4.95, -11.12, 1.0, 1.01]   
R5   [-13.1, 4.65, -11.21, 1.0, 1.01]  [-13.32, 4.11, -11.11, 1.0, 1.01]   

                                   C2                                  C3  \
R0  [-13.76, 5.78, -10.94, 1.0, 0.98]  [-13.94, 5.77, -10.87, 0.98, 0.95]   
R1    [-13.9, 5.8, -10.96, 1.0, 0.99]  [-14.02, 5.74, -10.88, 0.99, 0.97]   
R2   [-14.05, 5.77, -10.97, 1.0, 1.0]   [-14.48, 5.73, -10.92, 1.0, 0.99]   
R3   [-13.95, 5.56, -10.99, 1.0, 1.0]   [-13.96, 5.18, -10.85, 1.0, 0.99]   
R4    [-13.56, 5.3, -11.01, 1.0, 1.0]  [-13.75, 4.42, -10.72, 0.99, 0.95]   
R5    [-13.43, 4.41, -11.0, 1.0, 1.0]   [-13.62, 3.92, -10.7, 0.99, 0.96]   

                                    C4                                  C5  
R0   [-14.24, 5.8, -10.85, 0.96, 0.93]  [-13.87, 5.65, -10.62, 0.92, 0.85]  
R1   [-14.09, 5.18, -10.46, 0.9, 0.77]   [-14.0, 5.51, -10.59, 0.96, 0.88]  
R2   [-14.02, 5.23, -10.6, 0.95, 0.87]   [-14.36, 5.6, -10.72, 0.98, 0.94]  
R3  [-14.08, 5.04, -10.62, 0.98, 0.91]  [-14.26, 5.13, -10.55, 0.96, 0.88]  
R4  [-13.87, 4.76, -10.66, 0.99, 0.95]  [-14.05, 4.89, -10.55, 0.99, 0.94]  
R5  [-13.69, 3.91, -10.51, 0.98, 0.92]   [-14.14, 4.36, -10.55, 1.0, 0.98]

In [20]:
# 카파 고정, 델타 변동성 측정 (거리에 따른)
# 좌안 렌즈 근방